version: '3.8'

services:
  app:
    image: myapp:latest
    build:
      context: .
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - app-network

  reverse-proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
