version: '3.8'

services:
  app:
    image: myapp:latest
    build:
      context: .
    ports:
      - "8080" # Sadece dahili erişim için, harici port belirtmeye gerek yok
    restart: always
    networks:
      - app-network

  reverse-proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
